### PR TITLE
feat(i18n): Watch beabee content for locale changes

### PR DESCRIPTION
**Pull request by JumpLink**
Watch beabee content for locale changes by pulling the API.

* I use this to sync the telegram-bot language as soon as they are changed in beabee.
* I also added a `waitForUrl` util method to wait for the beabee api on bootstrapping the bot.

### CODE REVIEW

**Review by wpf500 — COMMENTED** [review]
I love the attempt to make this as pure as possible but I think this might be a bit over engineered :stuck_out_tongue:

In practice an instance's language basically never changes once it's been set up, and this solution generates **a lot** of API requests. I think it would be better just to have an endpoint we can push to.

This actually already exists for the intended use case (watching for locale changes)
https://github.com/beabee-communityrm/beabee/blob/master/src/core/services/OptionsService.ts#L123

The services all share an internal network in their Docker stack which they can use to communicate. Obviously it's very hacky at the moment, I'd love for this to just broadcast to the internal network, but I think it's better than polling the API so much. What do you think?

**Comment by JumpLink** [comment]
Okay, I can only get the content at the start and not watch it. My thought was that it would be easier to test the languages, which would save time

**Comment by JumpLink** [comment]
thanks that's better, I'll implement it

**Comment by JumpLink** [comment]
Do I just need to implement a reload controller to refetch the content?

**Comment by wpf500** [comment]
Yeah you can see the very simple route that gets created here for the legacy app, API and webook app:

https://github.com/beabee-communityrm/beabee/blob/master/src/core/server.ts#L13

It basically creates an internal HTTP server that listens to :4000, I'd do the same for the telegram bot too. Then just needs to refetch the content when it gets that signal.

Ideally we wouldn't reference the telegram bot in the core app but it might be the simplest thing to do for now, just behind an env var so it can be enabled/disabled.

You could do a quick bit of research into what it would take to create an internal broadcast messaging service like [RabbitMQ](https://www.rabbitmq.com/) that services can subscribe to, but if it's not really simple them just hardcode it for now.

**Comment by wpf500** [comment]
Or I know that people often use Redis for this sort of thing too: https://redis.com/solutions/use-cases/messaging/

**Comment by wpf500** [comment]
But just to emphasise: this is not a priority right now and hardcoding is also okay :upside_down_face:

**Comment by JumpLink** [comment]
As long as this communication is really only internal and cannot be intercepted, I think this is a good and simple solution. But maybe we should swap http with https

**Comment by wpf500** [comment]
Hmm I don't think you could use HTTPS here as app, api_app, etc. are internal names resolved by Docker's DNS so you'd only be able generate self signed certs in any case.

I guess in theory someone could accidentally expose :4000 to the outside world. Clients using our hosted solution will be fine but maybe we should add a secret or something just to be safe?

**Comment by JumpLink** [comment]
@wpf500 I have now also implemented the `NetworkCommunicatorService` here and replaced the pulling with pushing. It may make sense to outsource the `NetworkCommunicatorService` in order to be able to use it in different services, as we already have two implementations, this one uses `fetch` and would therefore theoretically be platform-independent

**Pull request merged**
