### PR TITLE
Update messages copy

### PR DESCRIPTION
**Pull request by rlafuente**

### CODE REVIEW

**Review by JumpLink — CHANGES_REQUESTED** [review]
@rlafuente Thank you! Can you please update the translations on the Google Sheet like we did on the Beabee Frontend? See  [telegram-bot/README.md#internationalisation](https://github.com/beabee-communityrm/telegram-bot/blob/main/telegram-bot/README.md#internationalisation) for more information.

**Comment by rlafuente** [comment]
Just finished copying over the fields to the locales spreadsheet. Since it's using CamelCase formatting, I rewrote the keynames to conform -- e.g. `response -> messages -> answer-with-truthy-or-falsy` becomes `bot.response.messages.answerWithTruthyOrFalsy`. Is this ok?

**Comment by JumpLink** [comment]
@rlafuente Yes it's okay but then you would also have to rename the keynames in the code so that the translations can still be found

**Comment by rlafuente** [comment]
Sure, let's do that. But since this is something out of the scope of the current task I'll add it in as a new trello card and we can pick it up in the next sprint

**Comment by JumpLink** [comment]
Should actually only be a search and replace...

**Comment by rlafuente** [comment]
ok I *think* I've gone through all of them now

**Review by JumpLink — APPROVED** [review]

**Comment by JumpLink** [comment]
@rlafuente I'm only now seeing that you haven't adjusted the translations in [Google Sheet](https://docs.google.com/spreadsheets/d/1l35DW5OMi-xM8HXek5Q1jOxsXScINqqpEvPWDlpBPX8/edit#gid=383159437)...

I have transferred the translations to the Google Sheet, but please check again for me to make sure I haven't made a mistake

**Comment by rlafuente** [comment]
Ah I didn't know this was using a dedicated sheet -- I added the strings to the [Beabee locales](https://docs.google.com/spreadsheets/d/1l35DW5OMi-xM8HXek5Q1jOxsXScINqqpEvPWDlpBPX8/edit#gid=0) sheet (line 925 onwards). I'm now signing off for the day but let's sync next week to be sure I didn't miss any other detail

**Comment by JumpLink** [comment]
@rlafuente Oh well, here was the misunderstanding, I [adjusted the link to the Google Sheet](https://github.com/beabee-communityrm/telegram-bot/pull/19/commits/281a06e21dc0ef81f613181758ea1bd828c3cc98) so that it points directly to the tab. Could you check that again and transfer it?

**Pull request merged**
